### ISSUE TITLE
Some roadmap

### ISSUE THREAD

**Issue by michaelzoidl** [entwicklerstube/takeoff#6]
### Features
- [ ] Add something like `takeoff --import my/file.js` to create a station from a existing file.
The prompt asks for another name, anything else is still the same like in the file.
- [ ] `takeoff --init` creates the initial `.takeoff` folder
- [ ] use `index.js` files as station instead of `__station.js` files
- [ ] Also support some kind of "use a existing template/file" instead of defining the body of the files in a station. 

### Code
- Move on from XOXO to Eslint with Cospired ™️ linter (similar to airbnb)
- Use RollupJS to compile the module

### General
- Document things in Wiki (User-Guide)
- Add some logo on the top
- Badges

---

Any other ideas / inspirations we should add? :) 
@bitcloud, @broon-s, @e110c0

**Comment by michaelzoidl** [comment]
Comment:
- Removed taskler without the need to replace it with listr
- Logo is on top
- Updated badges
- Moved from XOXO to eslint, but uses the default eslint style
